version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=chargepoints
      - DB_USERNAME=root
      - DB_PASSWORD=Home@123
      - QUEUE_CONNECTION=rabbitmq
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - mysql
      - rabbitmq

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chargepoints
      MYSQL_ROOT_PASSWORD: Home@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: laravel_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

# Volumes for persistent data
volumes:
  mysql_data:
  rabbitmq_data: